// create-product.dto.ts
// GENERATED BY THE SCRIPT. DO NOT EDIT.

import { IsString, IsNotEmpty } from 'class-validator';

export class CreateProductDto {
  @IsString()
  @IsNotEmpty()
  name: string;
}