// update-product.dto.ts
// GENERATED BY THE SCRIPT. DO NOT EDIT.

import { PartialType } from '@nestjs/mapped-types';
import { CreateProductDto } from './create-product.dto';

export class UpdateProductDto extends PartialType(CreateProductDto) {}